### PR TITLE
skeleton: test environment

### LINKED ISSUE #3: Set up of Travis
Set up of Travis on the github repository.

### LINKED ISSUE #4: Etablishing of Test module
Etablishing of a test's module and a docker file for launch it.

### PR DESCRIPTION
**Pull request by maiste**
* Add OUnit basic test environment (fixes #4)
* Add dockerfile builder and travis tests (fixes #3)

### CODE REVIEW

**Comment by xavitator** [comment]
How can we call a function declared in a file in Core folder ? To make some test with it.

**Comment by kolibs** [comment]
```ocaml
(* eos.ml *)
Core.File.function ...

(* core files : same as normal OCaml module call *)
File.function ...
```
But maybe we will simplify it later in eos with
```ocaml
 module Lib = Core.Main
```

**Comment by xavitator** [comment]
I wanted to say in a test file, not in eos file.

**Comment by kolibs** [comment]
Same as **eos.ml**.  I missed adding it in tests libraries (correct now).

**Review by xavitator — APPROVED** [review]

**Pull request merged**
